# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.
#
# Push the app to shinyapps.io when there's a change to the eiat data in aiti-flinders/eiat

name: push-app

on: workflow_dispatch

permissions:
  contents: read

jobs:
  deploy-eiat:
    runs-on: macOS-latest
  steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'
    - name: Check R and Rscript are available
      if: runner.os == 'macOS'
      run: |
        sudo ln -sf $R_HOME/bin/R /usr/local/bin
        sudo ln -sf $R_HOME/bin/Rscript /usr/local/bin
      env: 
        R_HOME: /Library/Frameworks/R.framework/Resources
    - name: Install packages
      env: 
        GITHUB_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        Rscript -e "install.packages(c('shiny', 'rsconnect', 'remotes', 'pkgload'), type = 'binary')"
        Rscript -e "remotes::install_deps(type = 'binary', force = FALSE, dependencies = TRUE)"
    - name: Push to shiny.io
      run: |
        Rscript -e "rsconnect::setAccountInfo(name = 'aiti', token = '${{secrets.SHINYAPPS_TOKEN}}', secret = '${{secrets.SHINYAPPS_SECRET}}')"
        Rscript -e "rsconnect::deployApp(appName = 'eiat')"
      
